Fix:Test dose not pass.
rami2076/a-star-by-java pull request #12
Opened 2021-01-03 00:49 UTC by rami2076

b部のコメントが未記載状態
todoが残っている状態

2021-01-14 14:58 UTC, SeasonFish requested changes
AStarPathFinder.javaまで見ました。

2021-01-14 14:58 UTC, SeasonFish commented on solution/src/main/java/org/astar/a/a/service/AStarPathFinderImpl.java
> +import org.astar.a.a.value_object.ChainNode;
アセンブリまたはディレクトリ構造を変えられませんか？
aだと違和感がすごいので。

2021-01-14 14:58 UTC, SeasonFish commented on solution/src/main/java/org/astar/a/a/service/AStarPathFinderImpl.java
> +     * 暫定的に探索済みの最短経路で無いと判定された経路(Node)を格納したリスト
OpenListのことでしょうか？
だったら「次に探索するノードのリスト」の意味のはずです。

2021-01-14 14:58 UTC, SeasonFish commented on solution/src/main/java/org/astar/a/SimpleRecursivePathFinder.java
> +        var result = findPathRecursively(width, height, startPoint, endPoint, obstacles.map(HashSet::new).orElseGet(HashSet::new));
.map(HashSet::new)が必要でしょうか？

2021-01-14 14:58 UTC, SeasonFish commented on solution/src/main/java/org/astar/a/a/service/AStarPathFinderImpl.java
> +        if (this.provisionalCloseSet.contains(newNode)) {
return !this.provisionalCloseSet.contains(newNode);

2021-01-14 14:58 UTC, SeasonFish commented on solution/src/main/java/org/astar/a/a/value_object/ChainNode.java
> +
ブロック最初と最後の空行を無くしてほしいです。
空行があったりなかったりするメソッドがありますので、統一感を保つ意図でもあります。

2021-01-14 14:58 UTC, SeasonFish commented on solution/src/main/java/org/astar/a/a/value_object/Coordinate.java
> +            Coordinate coordinate = (Coordinate) obj;
型宣言はvarにしましょう。これも統一感のためです。

2021-01-14 14:58 UTC, SeasonFish commented on solution/src/main/java/org/astar/a/a/value_object/CoordinateSystem.java
> +        return calculateDistance(coordinate, this.startCoordinate());
前回お話したように、gの計算が一個前のノードのgに+1した値にしてください。

2021-01-17 05:55 UTC, rami2076 commented on solution/src/main/java/org/astar/a/a/service/AStarPathFinderImpl.java
> +import org.astar.a.a.value_object.ChainNode;
構造変更しました。

2021-01-17 05:57 UTC, rami2076 commented on solution/src/main/java/org/astar/a/SimpleRecursivePathFinder.java
> +        var result = findPathRecursively(width, height, startPoint, endPoint, obstacles.map(HashSet::new).orElseGet(HashSet::new));
これは渡されるSetがimmuutableなSetを渡すようにしていたので必要になります。

2021-01-17 06:09 UTC, rami2076 commented on solution/src/main/java/org/astar/a/a/value_object/ChainNode.java
> +
対応しました。

2021-01-17 06:10 UTC, rami2076 commented on solution/src/main/java/org/astar/a/a/value_object/Coordinate.java
> +            Coordinate coordinate = (Coordinate) obj;
対応しました。

2021-01-17 06:11 UTC, rami2076 commented on solution/src/main/java/org/astar/a/a/value_object/CoordinateSystem.java
> +        return calculateDistance(coordinate, this.startCoordinate());
この関数は現在使われていないので削除する方向で回収致します。

2021-01-23 23:38 UTC, SeasonFish approved these changes

2021-01-23 23:39 UTC, merged